# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CvQ-DRIqtl1CEs9Meju9Ri5VOObncDyw
"""

import streamlit as st

st.write("hello world")